### ISSUE TITLE
config file path is error

### ISSUE THREAD

**Issue by bfrontend** [sanyuan0704/esbuild-web-app-scaffold#19]
in @ewas/cli/config 
![image](https://user-images.githubusercontent.com/40289489/147219761-42343eeb-b25d-42d8-b0b2-73fd32a5d700.png)

**Comment by sanyuan0704** [comment]
Oh，you may have seen the old version.I had updated it in latest version.
![image](https://user-images.githubusercontent.com/39261479/147220660-8ce0ece2-746d-483e-9da1-3880b9e19c8d.png)
