### ISSUE TITLE
npm init @ewas/esbuild-app get a error

### ISSUE THREAD

**Issue by bfrontend** [sanyuan0704/esbuild-web-app-scaffold#2]
![image](https://user-images.githubusercontent.com/40289489/146635033-a2738753-671d-4aed-bfde-22df42d1cee3.png)

**Comment by sanyuan0704** [comment]
Thanks for feedback, i will fix it soon.

**Comment by sanyuan0704** [comment]
I have fixed it.You  can try it again. Sorry for the break change.❤️

**Comment by bfrontend** [comment]
It still doesn't seem to work

**Comment by sanyuan0704** [comment]
***@***.******@***.***&quot;&nbsp;


---Original---
From: ***@***.***&gt;
Date: Sat, Dec 18, 2021 18:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [sanyuan0704/esbuild-web-app-scaffold] npm init @ewas/esbuild-app get a error (Issue #2)




 
It still doesn't seem to work
 
&mdash;

**Comment by sanyuan0704** [comment]
May be npm cache problem.You can  try `yarn create @ewas/esbuild-app`
